//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
//
//     NOTE : classe rendue PUBLIQUE (PublicResXFileCodeGenerator) afin d'être
//     accessible en XAML via {x:Static props:Resources.Clé}.
//     Si vous régénérez via Visual Studio, conservez l'outil personnalisé
//     « PublicResXFileCodeGenerator » dans les propriétés du fichier .resx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOLInfo.Properties {
    using System;


    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOLInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // ── Barre d'outils ────────────────────────────────────────────────

        public static string Toolbar_Sort {
            get { return ResourceManager.GetString("Toolbar_Sort", resourceCulture); }
        }

        public static string Toolbar_Favorites {
            get { return ResourceManager.GetString("Toolbar_Favorites", resourceCulture); }
        }

        public static string Toolbar_Damage {
            get { return ResourceManager.GetString("Toolbar_Damage", resourceCulture); }
        }

        public static string Toolbar_Range {
            get { return ResourceManager.GetString("Toolbar_Range", resourceCulture); }
        }

        public static string Toolbar_Classes {
            get { return ResourceManager.GetString("Toolbar_Classes", resourceCulture); }
        }

        public static string Toolbar_Difficulty {
            get { return ResourceManager.GetString("Toolbar_Difficulty", resourceCulture); }
        }

        public static string Toolbar_Resource {
            get { return ResourceManager.GetString("Toolbar_Resource", resourceCulture); }
        }

        // ── Filtres Dégâts / Portée ───────────────────────────────────────

        public static string Filter_All {
            get { return ResourceManager.GetString("Filter_All", resourceCulture); }
        }

        public static string Filter_Damage_AD {
            get { return ResourceManager.GetString("Filter_Damage_AD", resourceCulture); }
        }

        public static string Filter_Damage_AP {
            get { return ResourceManager.GetString("Filter_Damage_AP", resourceCulture); }
        }

        public static string Filter_Damage_Mixed {
            get { return ResourceManager.GetString("Filter_Damage_Mixed", resourceCulture); }
        }

        public static string Filter_Range_Melee {
            get { return ResourceManager.GetString("Filter_Range_Melee", resourceCulture); }
        }

        public static string Filter_Range_Ranged {
            get { return ResourceManager.GetString("Filter_Range_Ranged", resourceCulture); }
        }

        // ── Options de tri ────────────────────────────────────────────────

        public static string Sort_NameAsc {
            get { return ResourceManager.GetString("Sort_NameAsc", resourceCulture); }
        }

        public static string Sort_NameDesc {
            get { return ResourceManager.GetString("Sort_NameDesc", resourceCulture); }
        }

        public static string Sort_DifficultyAsc {
            get { return ResourceManager.GetString("Sort_DifficultyAsc", resourceCulture); }
        }

        public static string Sort_DifficultyDesc {
            get { return ResourceManager.GetString("Sort_DifficultyDesc", resourceCulture); }
        }

        // ── Page de détail ────────────────────────────────────────────────

        public static string Detail_Tab_Spells {
            get { return ResourceManager.GetString("Detail_Tab_Spells", resourceCulture); }
        }

        public static string Detail_Tab_General {
            get { return ResourceManager.GetString("Detail_Tab_General", resourceCulture); }
        }

        public static string Detail_Tab_Stats {
            get { return ResourceManager.GetString("Detail_Tab_Stats", resourceCulture); }
        }

        public static string Detail_Back {
            get { return ResourceManager.GetString("Detail_Back", resourceCulture); }
        }

        public static string Detail_LevelGain {
            get { return ResourceManager.GetString("Detail_LevelGain", resourceCulture); }
        }

        public static string Detail_Formulas {
            get { return ResourceManager.GetString("Detail_Formulas", resourceCulture); }
        }

        // ── Libellés de sorts ─────────────────────────────────────────────

        public static string Spell_Cooldown {
            get { return ResourceManager.GetString("Spell_Cooldown", resourceCulture); }
        }

        public static string Spell_Cost {
            get { return ResourceManager.GetString("Spell_Cost", resourceCulture); }
        }

        public static string Spell_Range {
            get { return ResourceManager.GetString("Spell_Range", resourceCulture); }
        }

        /// <summary>Modèle d'en-tête de rang. {0} = numéro de rang (ex : « Niv {0} »).</summary>
        public static string Spell_LevelHeader {
            get { return ResourceManager.GetString("Spell_LevelHeader", resourceCulture); }
        }

        // ── Classes de champions (filtre) ─────────────────────────────────

        public static string Tag_Fighter {
            get { return ResourceManager.GetString("Tag_Fighter", resourceCulture); }
        }

        public static string Tag_Tank {
            get { return ResourceManager.GetString("Tag_Tank", resourceCulture); }
        }

        public static string Tag_Mage {
            get { return ResourceManager.GetString("Tag_Mage", resourceCulture); }
        }

        public static string Tag_Assassin {
            get { return ResourceManager.GetString("Tag_Assassin", resourceCulture); }
        }

        public static string Tag_Marksman {
            get { return ResourceManager.GetString("Tag_Marksman", resourceCulture); }
        }

        public static string Tag_Support {
            get { return ResourceManager.GetString("Tag_Support", resourceCulture); }
        }

        // ── Ressources de champions (filtre) ──────────────────────────────

        public static string Resource_Mana {
            get { return ResourceManager.GetString("Resource_Mana", resourceCulture); }
        }

        public static string Resource_None {
            get { return ResourceManager.GetString("Resource_None", resourceCulture); }
        }

        public static string Resource_Energy {
            get { return ResourceManager.GetString("Resource_Energy", resourceCulture); }
        }

        public static string Resource_Other {
            get { return ResourceManager.GetString("Resource_Other", resourceCulture); }
        }

        // ── Statistiques (formules CDragon) ───────────────────────────────

        public static string Stat_AttackDamage {
            get { return ResourceManager.GetString("Stat_AttackDamage", resourceCulture); }
        }

        public static string Stat_AttackSpeed {
            get { return ResourceManager.GetString("Stat_AttackSpeed", resourceCulture); }
        }

        public static string Stat_AbilityPower {
            get { return ResourceManager.GetString("Stat_AbilityPower", resourceCulture); }
        }

        public static string Stat_Armor {
            get { return ResourceManager.GetString("Stat_Armor", resourceCulture); }
        }

        public static string Stat_MagicResist {
            get { return ResourceManager.GetString("Stat_MagicResist", resourceCulture); }
        }

        public static string Stat_Health {
            get { return ResourceManager.GetString("Stat_Health", resourceCulture); }
        }

        public static string Stat_MovementSpeed {
            get { return ResourceManager.GetString("Stat_MovementSpeed", resourceCulture); }
        }

        public static string Stat_CritChance {
            get { return ResourceManager.GetString("Stat_CritChance", resourceCulture); }
        }

        public static string Stat_HealthRegen {
            get { return ResourceManager.GetString("Stat_HealthRegen", resourceCulture); }
        }

        public static string Stat_Mana {
            get { return ResourceManager.GetString("Stat_Mana", resourceCulture); }
        }

        public static string Stat_ManaRegen {
            get { return ResourceManager.GetString("Stat_ManaRegen", resourceCulture); }
        }

        public static string Stat_AbilityHaste {
            get { return ResourceManager.GetString("Stat_AbilityHaste", resourceCulture); }
        }

        public static string Stat_Unknown {
            get { return ResourceManager.GetString("Stat_Unknown", resourceCulture); }
        }

        /// <summary>Suffixe « (base) » (avec espace initial).</summary>
        public static string StatSuffix_Base {
            get { return ResourceManager.GetString("StatSuffix_Base", resourceCulture); }
        }

        /// <summary>Suffixe « bonus » (avec espace initial).</summary>
        public static string StatSuffix_Bonus {
            get { return ResourceManager.GetString("StatSuffix_Bonus", resourceCulture); }
        }

        // ── Fragments de formules CDragon ─────────────────────────────────

        public static string Formula_Resource {
            get { return ResourceManager.GetString("Formula_Resource", resourceCulture); }
        }

        public static string Formula_PerLevel {
            get { return ResourceManager.GetString("Formula_PerLevel", resourceCulture); }
        }

        public static string Formula_LevelRange {
            get { return ResourceManager.GetString("Formula_LevelRange", resourceCulture); }
        }

        public static string Formula_Level3 {
            get { return ResourceManager.GetString("Formula_Level3", resourceCulture); }
        }

        public static string Formula_Level2 {
            get { return ResourceManager.GetString("Formula_Level2", resourceCulture); }
        }
    }
}
