//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOLInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOLInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ← Retour.
        /// </summary>
        public static string Detail_Back {
            get {
                return ResourceManager.GetString("Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formules (CDragon).
        /// </summary>
        public static string Detail_Formulas {
            get {
                return ResourceManager.GetString("Detail_Formulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gain par niveau.
        /// </summary>
        public static string Detail_LevelGain {
            get {
                return ResourceManager.GetString("Detail_LevelGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Général.
        /// </summary>
        public static string Detail_Tab_General {
            get {
                return ResourceManager.GetString("Detail_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sorts.
        /// </summary>
        public static string Detail_Tab_Spells {
            get {
                return ResourceManager.GetString("Detail_Tab_Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stats.
        /// </summary>
        public static string Detail_Tab_Stats {
            get {
                return ResourceManager.GetString("Detail_Tab_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous.
        /// </summary>
        public static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AD.
        /// </summary>
        public static string Filter_Damage_AD {
            get {
                return ResourceManager.GetString("Filter_Damage_AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AP.
        /// </summary>
        public static string Filter_Damage_AP {
            get {
                return ResourceManager.GetString("Filter_Damage_AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mixte.
        /// </summary>
        public static string Filter_Damage_Mixed {
            get {
                return ResourceManager.GetString("Filter_Damage_Mixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mêlée.
        /// </summary>
        public static string Filter_Range_Melee {
            get {
                return ResourceManager.GetString("Filter_Range_Melee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Distance.
        /// </summary>
        public static string Filter_Range_Ranged {
            get {
                return ResourceManager.GetString("Filter_Range_Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (niv.1/18).
        /// </summary>
        public static string Formula_Level2 {
            get {
                return ResourceManager.GetString("Formula_Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (niv.1/9/18).
        /// </summary>
        public static string Formula_Level3 {
            get {
                return ResourceManager.GetString("Formula_Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (niv. 1→18).
        /// </summary>
        public static string Formula_LevelRange {
            get {
                return ResourceManager.GetString("Formula_LevelRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (par niv.).
        /// </summary>
        public static string Formula_PerLevel {
            get {
                return ResourceManager.GetString("Formula_PerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ressource.
        /// </summary>
        public static string Formula_Resource {
            get {
                return ResourceManager.GetString("Formula_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivant.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Précédent.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Énergie.
        /// </summary>
        public static string Resource_Energy {
            get {
                return ResourceManager.GetString("Resource_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mana.
        /// </summary>
        public static string Resource_Mana {
            get {
                return ResourceManager.GetString("Resource_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun.
        /// </summary>
        public static string Resource_None {
            get {
                return ResourceManager.GetString("Resource_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autre.
        /// </summary>
        public static string Resource_Other {
            get {
                return ResourceManager.GetString("Resource_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Difficulté ↑.
        /// </summary>
        public static string Sort_DifficultyAsc {
            get {
                return ResourceManager.GetString("Sort_DifficultyAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Difficulté ↓.
        /// </summary>
        public static string Sort_DifficultyDesc {
            get {
                return ResourceManager.GetString("Sort_DifficultyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom A → Z.
        /// </summary>
        public static string Sort_NameAsc {
            get {
                return ResourceManager.GetString("Sort_NameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom Z → A.
        /// </summary>
        public static string Sort_NameDesc {
            get {
                return ResourceManager.GetString("Sort_NameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⏱ Recharge.
        /// </summary>
        public static string Spell_Cooldown {
            get {
                return ResourceManager.GetString("Spell_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 💧 Coût.
        /// </summary>
        public static string Spell_Cost {
            get {
                return ResourceManager.GetString("Spell_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🎨 Chromas disponibles.
        /// </summary>
        public static string Skin_ChromasAvailable {
            get {
                return ResourceManager.GetString("Skin_ChromasAvailable", resourceCulture);
            }
        }

        public static string StatPage_Level {
            get { return ResourceManager.GetString("StatPage_Level", resourceCulture); }
        }

        public static string StatLabel_Health {
            get { return ResourceManager.GetString("StatLabel_Health", resourceCulture); }
        }

        public static string StatLabel_HealthRegen {
            get { return ResourceManager.GetString("StatLabel_HealthRegen", resourceCulture); }
        }

        public static string StatLabel_Mana {
            get { return ResourceManager.GetString("StatLabel_Mana", resourceCulture); }
        }

        public static string StatLabel_ManaRegen {
            get { return ResourceManager.GetString("StatLabel_ManaRegen", resourceCulture); }
        }

        public static string StatLabel_Armor {
            get { return ResourceManager.GetString("StatLabel_Armor", resourceCulture); }
        }

        public static string StatLabel_MagicResist {
            get { return ResourceManager.GetString("StatLabel_MagicResist", resourceCulture); }
        }

        public static string StatLabel_AttackDamage {
            get { return ResourceManager.GetString("StatLabel_AttackDamage", resourceCulture); }
        }

        public static string StatLabel_AttackSpeed {
            get { return ResourceManager.GetString("StatLabel_AttackSpeed", resourceCulture); }
        }

        public static string StatLabel_MoveSpeed {
            get { return ResourceManager.GetString("StatLabel_MoveSpeed", resourceCulture); }
        }

        public static string StatLabel_AttackRange {
            get { return ResourceManager.GetString("StatLabel_AttackRange", resourceCulture); }
        }

        public static string StatLabel_CritChance {
            get { return ResourceManager.GetString("StatLabel_CritChance", resourceCulture); }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niv {0}.
        /// </summary>
        public static string Spell_LevelHeader {
            get {
                return ResourceManager.GetString("Spell_LevelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 🎯 Portée.
        /// </summary>
        public static string Spell_Range {
            get {
                return ResourceManager.GetString("Spell_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à hâte.
        /// </summary>
        public static string Stat_AbilityHaste {
            get {
                return ResourceManager.GetString("Stat_AbilityHaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PA.
        /// </summary>
        public static string Stat_AbilityPower {
            get {
                return ResourceManager.GetString("Stat_AbilityPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à armure.
        /// </summary>
        public static string Stat_Armor {
            get {
                return ResourceManager.GetString("Stat_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AD.
        /// </summary>
        public static string Stat_AttackDamage {
            get {
                return ResourceManager.GetString("Stat_AttackDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vit. attaque.
        /// </summary>
        public static string Stat_AttackSpeed {
            get {
                return ResourceManager.GetString("Stat_AttackSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chance crit..
        /// </summary>
        public static string Stat_CritChance {
            get {
                return ResourceManager.GetString("Stat_CritChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PV.
        /// </summary>
        public static string Stat_Health {
            get {
                return ResourceManager.GetString("Stat_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à régén. PV.
        /// </summary>
        public static string Stat_HealthRegen {
            get {
                return ResourceManager.GetString("Stat_HealthRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RM.
        /// </summary>
        public static string Stat_MagicResist {
            get {
                return ResourceManager.GetString("Stat_MagicResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mana.
        /// </summary>
        public static string Stat_Mana {
            get {
                return ResourceManager.GetString("Stat_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à régén. mana.
        /// </summary>
        public static string Stat_ManaRegen {
            get {
                return ResourceManager.GetString("Stat_ManaRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vit. dépl..
        /// </summary>
        public static string Stat_MovementSpeed {
            get {
                return ResourceManager.GetString("Stat_MovementSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à stat inconnue.
        /// </summary>
        public static string Stat_Unknown {
            get {
                return ResourceManager.GetString("Stat_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  (base).
        /// </summary>
        public static string StatSuffix_Base {
            get {
                return ResourceManager.GetString("StatSuffix_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  bonus.
        /// </summary>
        public static string StatSuffix_Bonus {
            get {
                return ResourceManager.GetString("StatSuffix_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assassin.
        /// </summary>
        public static string Tag_Assassin {
            get {
                return ResourceManager.GetString("Tag_Assassin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Combattant.
        /// </summary>
        public static string Tag_Fighter {
            get {
                return ResourceManager.GetString("Tag_Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mage.
        /// </summary>
        public static string Tag_Mage {
            get {
                return ResourceManager.GetString("Tag_Mage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tireur.
        /// </summary>
        public static string Tag_Marksman {
            get {
                return ResourceManager.GetString("Tag_Marksman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Support.
        /// </summary>
        public static string Tag_Support {
            get {
                return ResourceManager.GetString("Tag_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tank.
        /// </summary>
        public static string Tag_Tank {
            get {
                return ResourceManager.GetString("Tag_Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Classes :.
        /// </summary>
        public static string Toolbar_Classes {
            get {
                return ResourceManager.GetString("Toolbar_Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dégâts :.
        /// </summary>
        public static string Toolbar_Damage {
            get {
                return ResourceManager.GetString("Toolbar_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Difficulté :.
        /// </summary>
        public static string Toolbar_Difficulty {
            get {
                return ResourceManager.GetString("Toolbar_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Favoris.
        /// </summary>
        public static string Toolbar_Favorites {
            get {
                return ResourceManager.GetString("Toolbar_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Portée :.
        /// </summary>
        public static string Toolbar_Range {
            get {
                return ResourceManager.GetString("Toolbar_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ressource :.
        /// </summary>
        public static string Toolbar_Resource {
            get {
                return ResourceManager.GetString("Toolbar_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trier :.
        /// </summary>
        public static string Toolbar_Sort {
            get {
                return ResourceManager.GetString("Toolbar_Sort", resourceCulture);
            }
        }
    }
}
